sudo: false
language: clojure
lein: 2.9.1
dist: trusty   # Because Travis CI's support for older versions of Java is *garbage*

jdk:
  - oraclejdk8
  - openjdk11   # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

script: lein do check, test, cljsbuild test
